<?php

return [
    'bili'            => ['b23.tv', 'www.bilibili.com'],
    'douyin'          => ['douyin.com', 'iesdouyin.com'],
    'huoshan'         => ['huoshan.com'],
    'kuaishou'        => ['ziyang.m.kspkg.com', 'kuaishou.com', 'gifshow.com', 'chenzhongtech.com', 'v.kuaishouapp.com'],
    'livideo'         => ['www.pearvideo.com'],
    'meipai'          => ['www.meipai.com'],
    'momo'            => ['immomo.com'],
    'pipigaoxiao'     => ['ippzone.com'],
    'pipixia'         => ['pipix.com'],
    'quanminggaoxiao' => ['longxia.music.xiaomi.com'],
    'shuabao'         => ['h5.shua8cn.com', 'm.shua8cn.com'],
    'toutiao'         => ['toutiaoimg.com', 'toutiaoimg.cn'],
    'weishi'          => ['weishi.qq.com'],
    'xiaokaxiu'       => ['mobile.xiaokaxiu.com'],
    'xigua'           => ['xigua.com'],
    'zuiyou'          => ['izuiyou.com'],
    'weibo'           => ['weibo.com', 'weibo.cn'],
    'newweibo'        => ['video.weibo.com/show'],
    'miaopai'         => ['miaopai.com'],
    'qqvideo'         => ['m.v.qq.com'],
    'taobao'          => ['h5.m.taobao.com', 'm.tb.cn'],
];